default:
  image: ubuntu:latest

job_compile:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install curl clang cmake git libdbus-1-dev libglib2.0-dev linux-headers-aws-edge llvm make pkg-config python3
    - git clone https://github.com/jarro2783/cxxopts --depth 1 --branch $(curl -s https://api.github.com/repos/jarro2783/cxxopts/releases/latest | grep tag_name | cut -d '"' -f 4) /usr/local/src/cxxopts
    - ln -s ../src/cxxopts/include/cxxopts.hpp /usr/local/include/cxxopts.hpp
  script:
    - make MODE=prod LINHEADERS=$(realpath /usr/src/linux-aws-*-headers-*/include/uapi/linux)
  artifacts:
    paths:
      - bin/minimzd
  cache:
    key: compile-$CI_COMMIT_REF_SLUG
    paths:
      - "generated/*"
      - "obj/*"
      - "third-party/**.a"

job_release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - ':'
  release:
    tag_name: $CI_COMMIT_TAG
    description: $CI_COMMIT_TAG_MESSAGE
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
